apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogeks-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: catalogeks
  template:
    metadata:
      labels:
        app: catalogeks
    spec:
      containers:
      - name: catalogeks
        image: 339712837349.dkr.ecr.eu-west-1.amazonaws.com/catalogeks:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 9001
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
