apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogeks-deployment
spec:
  replicas: 1  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0  
  selector:
    matchLabels:
      app: catalogeks
  template:
    metadata:
      labels:
        app: catalogeks
    spec:
      containers:
      - name: catalogeks
        image: 339712837349.dkr.ecr.eu-west-1.amazonaws.com/catalogeks:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
        resources:
          requests:
            memory: "256Mi"  
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "512m"
        readinessProbe:
          httpGet:
            path:  /actuator/health
            port: 9001
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3